### ISSUE TITLE
Does this match the current spec?

### ISSUE THREAD

**Issue by SonarBeserk** [wirepair/netcode#11]
I am trying to use a code generated by https://github.com/wirepair/netcode/blob/master/examples/server/server.go to pass along to the https://github.com/KillaMaaki/Unity-Netcode.IO client after decoding the base64 string to bytes. I can't tell which version has the differing format.

**Comment by wirepair** [comment]
Hello @SonarBeserk,
I'm unfamiliar with the Unity port, did you try against the master C repository to see if it works there?

**Comment by SonarBeserk** [comment]
I plan to take a look when I get some free time or it's the weekend. I am not familiar with working against C code bases directly. From testing against the .net code it seems that it does not like to convert from base64 to a 2048 byte array so the issue may be there.

**Comment by SonarBeserk** [comment]
The issue is in the C# code, Ill take it up with them. The issue seems to be that ipv6 was not set to be usable and there is some sort of issue parsing the ipv6 address. I am unsure of which side is the part that doesnt match correctly.
