### ISSUE TITLE
RecvPayload inconsistency

### ISSUE THREAD

**Issue by toqueteos** [wirepair/netcode#5]
Hello again,

I've continued my testing (still a side project, not much time available) and found that `Server.RecvPayload` using client indexes makes `SendPayloadToClient` pretty hard to use because it uses client ids instead.

How can I match those? I'm missing a translate step for `clientIndex <-> clientId`.

**EDIT:** Having two different client identifiers feels like a bad idea. Ofc I've seen `Server.getClientIndexByClientId` which does the translation I want, but that's private. Making it public would solve this issue BUT doesn't seem like the way to go. Everything but `SendPayloadToClient` uses clientIds, let's use those everywhere.

**Comment by gafferongames** [comment]
My advice is to please tend to prefer clientIndex when identifiying clients, not client Id. Then, have a nice function to get the client id for a particular client index.

**Comment by wirepair** [comment]
Temporarily I can make the getClientIndexById method public. I'd really like to get this thing rewritten though :/.

**Comment by gafferongames** [comment]
@toqueteos Are you able to hop on as a maintainer? It seems like @wirepair could use a hand

**Comment by toqueteos** [comment]
@gafferongames I wouldn't mind being a maintainer but there's no rush. I'm making progress, although veeeeery sloooooow on making this more idiomatic and close to the C library 💪  

EDIT: I can be the European timezone backup of you two 😄

**Comment by gafferongames** [comment]
No rush at all. Marathon not a sprint!

**Comment by wirepair** [comment]
I made GetClientIndexById public so i'm going to close this one.
