### ISSUE TITLE
Incorrect IPv6 UDPAddr read/writing

### ISSUE THREAD

**Issue by toqueteos** [wirepair/netcode#8]
Using `2001:db8::68` as IPv6 address breaks tests.

I've taken a look at the IPv6 read/write code and found [this][1]. It seems one of the two bytes is being ignored. I'm having trouble fixing the test to work with lots of IPv6 addresses (those with one or more components over 255).

/cc @wirepair @gafferongames

[1]: https://github.com/wirepair/netcode/blob/89fd4ed2c8f6eb786fac06216f7db7857547e18d/connect_token_shared.go#L135-L139

**Comment by wirepair** [comment]
Nice find!
